const common = require('./common')
const { dist, helper: { requireNpmRegex, replaceNpm } } = common
const fs = require('fs')
const gulp = require('gulp')
const $ = require('gulp-load-plugins')()

gulp.task('build:script', () =>
  gulp.src('src/**/*.js')
    .pipe($.plumber())
    .pipe($.babel({
      presets: ['env', 'stage-2']
    }))
    .pipe($.replace(requireNpmRegex, replaceNpm))
    .pipe($.uglify())
    .pipe(gulp.dest(dist))
)

gulp.task('build:less', _ =>
  gulp.src('src/**/*.less')
    .pipe($.plumber())
    .pipe($.less())
    .pipe($.cssnano())
    .pipe($.rename({ extname: '.wxss' }))
    .pipe(gulp.dest(dist))
)

gulp.task('build:wxss', _ =>
  gulp.src('src/**/*.wxss')
    .pipe($.cssnano())
    .pipe(gulp.dest(dist))
)

gulp.task('build:wxml', _ =>
  gulp.src('src/**/*.wxml')
    .pipe($.htmlmin({
      collapseWhitespace: true,
      includeAutoGeneratedTags: false,
      keepClosingSlash: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
    }))
    .pipe(gulp.dest(dist))
)

gulp.task('build:json', _ =>
  gulp.src('src/**/*.json')
    .pipe($.jsonminify())
    .pipe(gulp.dest(dist))
)

gulp.task('build:image', _ =>
  gulp.src(['src/**/*.{jpg,jpeg,png,gif,svg}'])
    .pipe($.imagemin())
    .pipe(gulp.dest(dist))
)

gulp.task('build:webpack', ['webpack'])